{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4745c5ec-25b6-41f3-9b8b-d2d94990bb33",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-08-11 09:14:11.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.487 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.507 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.530 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.533 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.558 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-08-11 09:14:11.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# inventory_app.py\n",
    "import streamlit as st\n",
    "import csv\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "# File name\n",
    "filename = 'manual_data.csv'\n",
    "\n",
    "# Options\n",
    "satuan_options = ['Meter', 'kg', 'liter', 'buah']\n",
    "tempat_options = ['Gudang lantai 1', 'Gudang A lantai 4', 'Gudang B lantai 4', 'Gudang lantai 6']\n",
    "\n",
    "# Create CSV with header if not exists\n",
    "if not os.path.exists(filename):\n",
    "    with open(filename, 'w', newline='') as f:\n",
    "        writer = csv.writer(f)\n",
    "        writer.writerow(['Nama', 'Jumlah', 'Satuan', 'Tempat', 'Tanggal'])\n",
    "\n",
    "st.title(\"📦 Inventory Management App\")\n",
    "\n",
    "# Sidebar menu\n",
    "menu = st.sidebar.radio(\"Menu\", [\"Tambah Item\", \"Kurangi Item\", \"Pindahkan Item\", \"Lihat CSV\"])\n",
    "\n",
    "# Load CSV data\n",
    "def load_data():\n",
    "    with open(filename, 'r', newline='') as f:\n",
    "        return list(csv.DictReader(f))\n",
    "\n",
    "# Save CSV data\n",
    "def save_data(rows):\n",
    "    with open(filename, 'w', newline='') as f:\n",
    "        fieldnames = ['Nama', 'Jumlah', 'Satuan', 'Tempat', 'Tanggal']\n",
    "        writer = csv.DictWriter(f, fieldnames=fieldnames)\n",
    "        writer.writeheader()\n",
    "        writer.writerows(rows)\n",
    "\n",
    "# ---- ADD ITEM ----\n",
    "if menu == \"Tambah Item\":\n",
    "    st.header(\"Tambah / Update Item\")\n",
    "    nama = st.text_input(\"Nama\")\n",
    "    jumlah = st.number_input(\"Jumlah\", min_value=1, value=1)\n",
    "    satuan = st.selectbox(\"Satuan\", satuan_options)\n",
    "    tempat = st.selectbox(\"Tempat\", tempat_options)\n",
    "\n",
    "    if st.button(\"Submit\"):\n",
    "        rows = load_data()\n",
    "        found = False\n",
    "\n",
    "        for row in rows:\n",
    "            if (row['Nama'].strip().lower() == nama.lower() and\n",
    "                row['Satuan'] == satuan and\n",
    "                row['Tempat'] == tempat):\n",
    "                row['Jumlah'] = str(int(row['Jumlah']) + jumlah)\n",
    "                row['Tanggal'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "                found = True\n",
    "                break\n",
    "\n",
    "        if not found:\n",
    "            rows.append({\n",
    "                'Nama': nama,\n",
    "                'Jumlah': str(jumlah),\n",
    "                'Satuan': satuan,\n",
    "                'Tempat': tempat,\n",
    "                'Tanggal': datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "            })\n",
    "\n",
    "        save_data(rows)\n",
    "        st.success(f\"✅ Data '{nama}' berhasil ditambahkan / diperbarui.\")\n",
    "\n",
    "# ---- DECREASE ITEM ----\n",
    "elif menu == \"Kurangi Item\":\n",
    "    st.header(\"Kurangi Item\")\n",
    "    nama = st.text_input(\"Nama\")\n",
    "    jumlah = st.number_input(\"Jumlah yang dikurangi\", min_value=1, value=1)\n",
    "    satuan = st.selectbox(\"Satuan\", satuan_options)\n",
    "    tempat = st.selectbox(\"Tempat\", tempat_options)\n",
    "\n",
    "    if st.button(\"Kurangi\"):\n",
    "        rows = load_data()\n",
    "        updated_rows = []\n",
    "        found = False\n",
    "\n",
    "        for row in rows:\n",
    "            if (row['Nama'].strip().lower() == nama.lower() and\n",
    "                row['Satuan'] == satuan and\n",
    "                row['Tempat'] == tempat):\n",
    "                current_qty = int(row['Jumlah'])\n",
    "                if current_qty < jumlah:\n",
    "                    st.error(f\"❌ Jumlah yang diminta ({jumlah}) melebihi stok ({current_qty}).\")\n",
    "                    save_data(rows)\n",
    "                    st.stop()\n",
    "                elif current_qty == jumlah:\n",
    "                    st.info(f\"🗑️ Item '{nama}' dihapus dari lokasi.\")\n",
    "                    found = True\n",
    "                    continue\n",
    "                else:\n",
    "                    row['Jumlah'] = str(current_qty - jumlah)\n",
    "                    row['Tanggal'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "                    st.success(f\"➖ Berhasil mengurangi {jumlah} {satuan} dari '{nama}'.\")\n",
    "                    found = True\n",
    "            updated_rows.append(row)\n",
    "\n",
    "        if not found:\n",
    "            st.error(\"❌ Item tidak ditemukan.\")\n",
    "        else:\n",
    "            save_data(updated_rows)\n",
    "\n",
    "# ---- MOVE ITEM ----\n",
    "elif menu == \"Pindahkan Item\":\n",
    "    st.header(\"Pindahkan Item\")\n",
    "    nama = st.text_input(\"Nama\")\n",
    "    jumlah = st.number_input(\"Jumlah dipindahkan\", min_value=1, value=1)\n",
    "    satuan = st.selectbox(\"Satuan\", satuan_options)\n",
    "    source_tempat = st.selectbox(\"Dari\", tempat_options)\n",
    "    dest_tempat = st.selectbox(\"Ke\", tempat_options)\n",
    "\n",
    "    if st.button(\"Pindahkan\"):\n",
    "        if source_tempat == dest_tempat:\n",
    "            st.error(\"⚠️ Lokasi asal dan tujuan tidak boleh sama.\")\n",
    "        else:\n",
    "            rows = load_data()\n",
    "            updated_rows = []\n",
    "            found = False\n",
    "\n",
    "            for row in rows:\n",
    "                if (row['Nama'].strip().lower() == nama.lower() and\n",
    "                    row['Satuan'] == satuan and\n",
    "                    row['Tempat'] == source_tempat):\n",
    "                    current_qty = int(row['Jumlah'])\n",
    "                    if current_qty < jumlah:\n",
    "                        st.error(f\"❌ Stok di {source_tempat} tidak cukup ({current_qty}).\")\n",
    "                        save_data(rows)\n",
    "                        st.stop()\n",
    "                    elif current_qty == jumlah:\n",
    "                        found = True\n",
    "                        continue\n",
    "                    else:\n",
    "                        row['Jumlah'] = str(current_qty - jumlah)\n",
    "                        row['Tanggal'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "                        found = True\n",
    "                updated_rows.append(row)\n",
    "\n",
    "            if not found:\n",
    "                st.error(f\"❌ Item tidak ditemukan di {source_tempat}.\")\n",
    "            else:\n",
    "                # Tambah ke lokasi tujuan\n",
    "                merged = False\n",
    "                for row in updated_rows:\n",
    "                    if (row['Nama'].strip().lower() == nama.lower() and\n",
    "                        row['Satuan'] == satuan and\n",
    "                        row['Tempat'] == dest_tempat):\n",
    "                        row['Jumlah'] = str(int(row['Jumlah']) + jumlah)\n",
    "                        row['Tanggal'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "                        merged = True\n",
    "                        break\n",
    "                if not merged:\n",
    "                    updated_rows.append({\n",
    "                        'Nama': nama,\n",
    "                        'Jumlah': str(jumlah),\n",
    "                        'Satuan': satuan,\n",
    "                        'Tempat': dest_tempat,\n",
    "                        'Tanggal': datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n",
    "                    })\n",
    "\n",
    "                save_data(updated_rows)\n",
    "                st.success(f\"✅ {jumlah} {satuan} dari {source_tempat} berhasil dipindahkan ke {dest_tempat}.\")\n",
    "\n",
    "# ---- DISPLAY CSV ----\n",
    "elif menu == \"Lihat CSV\":\n",
    "    st.header(\"📄 Data Inventory\")\n",
    "    rows = load_data()\n",
    "    if rows:\n",
    "        st.dataframe(rows)\n",
    "    else:\n",
    "        st.info(\"📂 Data masih kosong.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "311b4e8c-8a28-4142-abb8-463ae51dc4a3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
